# Generated by Django 3.0.3 on 2020-06-23 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('class_title', models.CharField(max_length=100)),
                ('class_url', models.CharField(max_length=100)),
                ('class_sku', models.IntegerField(primary_key=True, serialize=False)),
                ('class_image', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['class_title'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['image_url'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('project_url', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Course')),
            ],
            options={
                'ordering': ['project_title'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=100)),
                ('label_confidence', models.FloatField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Image')),
            ],
            options={
                'ordering': ['label_name'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Project'),
        ),
    ]
